# Generated by Django 4.2 on 2023-05-01 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fan', '0002_subscription_delete_newsletter_advertisement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='subscriptions',
            field=models.ManyToManyField(related_name='ads_subscriptions', to='fan.subscription'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='fan.customuser'),
        ),
    ]
