# Generated by Django 4.2 on 2023-05-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fan', '0004_customuser_first_name_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to='fan.subscription'),
        ),
    ]
