# Generated by Django 4.2 on 2023-05-01 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fan', '0005_alter_advertisement_subscriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TANKS', 'Танки'), ('HEALERS', 'Хилы'), ('DPS', 'ДД'), ('TRADERS', 'Торговцы'), ('GUILDMASTERS', 'Гилдмастеры'), ('QUESTGIVERS', 'Квестгиверы'), ('BLACKSMITHS', 'Кузнецы'), ('LEATHERWORKERS', 'Кожевники'), ('ALCHEMY', 'Зельевары'), ('MAGES', 'Мастера заклинаний')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_subscriptions', to='fan.customuser')),
            ],
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='advertisements', to='fan.adsubscription'),
        ),
    ]
